CREATE TABLE `aqi_details` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(45) DEFAULT NULL,
  `AQI_VALUE` varchar(45) DEFAULT NULL,
  `CATEGORY` varchar(45) DEFAULT NULL,
  `PM_DAILY` varchar(45) DEFAULT NULL,
  `CO2_DAILY` varchar(45) DEFAULT NULL,
  `AQI_DAILY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
